%% 
function HeartFailurePredictionGUI()

    mainFig = figure('Name', 'Heart Failure Mortality Prediction System', ...
                     'NumberTitle', 'off', ...
                     'MenuBar', 'none', ...
                     'ToolBar', 'none', ...
                     'Resize', 'on', ...
                     'Position', [50, 50, 1600, 900], ...
                     'Color', [0.95 0.96 0.98], ...
                     'CloseRequestFcn', @closeGUI);
    
    colors = struct();
    colors.primary = [0.125, 0.463, 0.706];
    colors.secondary = [0.286, 0.239, 0.545];
    colors.success = [0.153, 0.682, 0.376];
    colors.warning = [1, 0.753, 0.145];
    colors.danger = [0.906, 0.298, 0.235];
    colors.background = [0.95 0.96 0.98];
    colors.cardBg = [1 1 1];
    colors.lightGray = [0.97 0.97 0.97];
    colors.medGray = [0.85 0.86 0.88];
    colors.darkGray = [0.2 0.2 0.25];
    colors.textPrimary = [0.15 0.15 0.2];
    colors.textSecondary = [0.4 0.4 0.45];
    
    handles = struct();
    handles.colors = colors;
    handles.currentResult = [];
    handles.models = [];
    handles.populationData = [];
    
    if ~exist('saved_models/heart_failure_models.mat', 'file')
        createWelcomeScreen();
        return;
    end
    
    try
        loadedData = load('saved_models/heart_failure_models.mat');
        handles.models = loadedData;
        
        if exist('heart_failure_clinical_records_dataset.csv', 'file')
            handles.populationData = readtable('heart_failure_clinical_records_dataset.csv');
        end
    catch ME
        errordlg(['Error loading models: ' ME.message], 'Model Loading Error');
        return;
    end
    
    createModernHeader();
    createModernInputPanel();
    createModernControlPanel();
    createModernResultsPanel();
    createModernFooter();
    
    guidata(mainFig, handles);
    
    function createWelcomeScreen()
        clf(mainFig);
        set(mainFig, 'Color', colors.cardBg);
        
        axes('Parent', mainFig, 'Position', [0 0.7 1 0.3], 'Visible', 'off');
        rectangle('Position', [0 0 1 1], 'FaceColor', colors.primary, 'EdgeColor', 'none');
        text(0.5, 0.6, 'Heart Failure Prediction System', ...
             'FontSize', 36, 'FontWeight', 'bold', 'Color', colors.cardBg, ...
             'HorizontalAlignment', 'center');
        
        uipanel('Position', [0.3 0.35 0.4 0.25], 'BackgroundColor', colors.cardBg, ...
                'BorderType', 'none', 'ShadowColor', colors.medGray);
        
        uicontrol('Style', 'text', ...
                  'String', sprintf('Models Not Found\n\nPlease run: A2_with_export.m\nto train models first'), ...
                  'Position', [0.35*1600 0.38*900 0.3*1600 0.15*900], ...
                  'FontSize', 16, 'BackgroundColor', colors.cardBg);
        
        uicontrol('Style', 'pushbutton', 'String', 'Close', ...
                  'Position', [0.45*1600 0.25*900 0.1*1600 0.06*900], ...
                  'FontSize', 14, 'Callback', @(~,~)close(mainFig), ...
                  'BackgroundColor', colors.primary, 'ForegroundColor', colors.cardBg);
    end
    
    function createModernHeader()
        headerPanel = uipanel('Parent', mainFig, ...
                              'Units', 'normalized', ...
                              'Position', [0 0.90 1 0.10], ...
                              'BackgroundColor', colors.primary, ...
                              'BorderType', 'none');
        
        uicontrol('Parent', headerPanel, 'Style', 'text', ...
                  'String', 'Heart Failure Mortality Prediction', ...
                  'Units', 'normalized', 'Position', [0.03 0.35 0.6 0.5], ...
                  'FontSize', 28, 'FontWeight', 'bold', ...
                  'ForegroundColor', colors.cardBg, ...
                  'BackgroundColor', colors.primary, ...
                  'HorizontalAlignment', 'left');
        
        uicontrol('Parent', headerPanel, 'Style', 'text', ...
                  'String', 'Advanced Clinical Decision Support System - Powered by Machine Learning', ...
                  'Units', 'normalized', 'Position', [0.03 0.15 0.6 0.25], ...
                  'FontSize', 14, 'ForegroundColor', [0.9 0.9 0.95], ...
                  'BackgroundColor', colors.primary, ...
                  'HorizontalAlignment', 'left');
        
        versionPanel = uipanel('Parent', headerPanel, ...
                              'Units', 'normalized', ...
                              'Position', [0.88 0.25 0.1 0.5], ...
                              'BackgroundColor', colors.secondary, ...
                              'BorderType', 'none');
        
        uicontrol('Parent', versionPanel, 'Style', 'text', ...
                  'String', 'v3.0 Pro', ...
                  'Units', 'normalized', 'Position', [0 0.1 1 0.8], ...
                  'FontSize', 14, 'FontWeight', 'bold', ...
                  'ForegroundColor', colors.cardBg, ...
                  'BackgroundColor', colors.secondary, ...
                  'HorizontalAlignment', 'center');
    end
    
    function createModernInputPanel()
        inputPanel = uipanel('Parent', mainFig, ...
                             'Units', 'normalized', ...
                             'Position', [0.02 0.32 0.30 0.56], ...
                             'BackgroundColor', colors.cardBg, ...
                             'BorderType', 'line', ...
                             'BorderWidth', 1, ...
                             'HighlightColor', colors.medGray);
        
        uicontrol('Parent', inputPanel, 'Style', 'text', ...
                  'String', 'Patient Clinical Data', ...
                  'Units', 'normalized', 'Position', [0.05 0.955 0.9 0.035], ...
                  'FontSize', 16, 'FontWeight', 'bold', ...
                  'HorizontalAlignment', 'left', ...
                  'BackgroundColor', colors.cardBg, ...
                  'ForegroundColor', colors.textPrimary);

        features = {
            'Demographics', '', '', '', 'header';
            'Age', 'years', '40-95', 'age', 'input';
            'Sex', '0=Female, 1=Male', '0 or 1', 'sex', 'input';
            '', '', '', '', 'spacer';
            'Clinical Measurements', '', '', '', 'header';
            'Ejection Fraction', '%', '14-80', 'ef', 'input';
            'Serum Creatinine', 'mg/dL', '0.5-9.4', 'creatinine', 'input';
            'Serum Sodium', 'mEq/L', '113-148', 'sodium', 'input';
            'Creatinine Phosphokinase', 'mcg/L', '23-7861', 'cpk', 'input';
            'Platelets', 'kiloplatelets/mL', '25k-850k', 'platelets', 'input';
            '', '', '', '', 'spacer';
            'Medical Conditions', '', '', '', 'header';
            'Anaemia', '0=No, 1=Yes', '0 or 1', 'anaemia', 'input';
            'Diabetes', '0=No, 1=Yes', '0 or 1', 'diabetes', 'input';
            'High Blood Pressure', '0=No, 1=Yes', '0 or 1', 'hbp', 'input';
            'Smoking', '0=No, 1=Yes', '0 or 1', 'smoking', 'input';
            '', '', '', '', 'spacer';
            'Follow-up Period', '', '', '', 'header';
            'Follow-up Period', 'days', '4-285', 'time', 'input'
        };
        
        yPos = 0.89;
        
        for i = 1:size(features, 1)
            if strcmp(features{i, 5}, 'header')
                uicontrol('Parent', inputPanel, 'Style', 'text', ...
                          'String', features{i, 1}, ...
                          'Units', 'normalized', ...
                          'Position', [0.05 yPos 0.9 0.035], ...
                          'FontSize', 13, 'FontWeight', 'bold', ...
                          'HorizontalAlignment', 'left', ...
                          'BackgroundColor', colors.lightGray, ...
                          'ForegroundColor', colors.primary);
                yPos = yPos - 0.045;
                
            elseif strcmp(features{i, 5}, 'spacer')
                yPos = yPos - 0.025;
                
            elseif strcmp(features{i, 5}, 'input')
                uicontrol('Parent', inputPanel, 'Style', 'text', ...
                          'String', features{i, 1}, ...
                          'Units', 'normalized', ...
                          'Position', [0.08 yPos 0.38 0.032], ...
                          'FontSize', 11, ...
                          'HorizontalAlignment', 'left', ...
                          'BackgroundColor', colors.cardBg, ...
                          'ForegroundColor', colors.textPrimary);
                
                handles.(['input_' features{i, 4}]) = uicontrol('Parent', inputPanel, ...
                          'Style', 'edit', ...
                          'Units', 'normalized', ...
                          'Position', [0.48 yPos 0.22 0.036], ...
                          'FontSize', 11, ...
                          'BackgroundColor', colors.lightGray);
                
                uicontrol('Parent', inputPanel, 'Style', 'text', ...
                          'String', features{i, 2}, ...
                          'Units', 'normalized', ...
                          'Position', [0.71 yPos 0.25 0.032], ...
                          'FontSize', 9, ...
                          'HorizontalAlignment', 'left', ...
                          'BackgroundColor', colors.cardBg, ...
                          'ForegroundColor', colors.textSecondary);
                
                yPos = yPos - 0.042;
            end
        end
        
        uicontrol('Parent', inputPanel, 'Style', 'pushbutton', ...
                  'String', '✓ High Risk Example', ...
                  'Units', 'normalized', ...
                  'Position', [0.05 0.045 0.28 0.042], ...
                  'FontSize', 10, ...
                  'Callback', @loadHighRiskExample, ...
                  'BackgroundColor', colors.danger, ...
                  'ForegroundColor', colors.cardBg, ...
                  'FontWeight', 'bold');
        
        uicontrol('Parent', inputPanel, 'Style', 'pushbutton', ...
                  'String', '✓ Low Risk Example', ...
                  'Units', 'normalized', ...
                  'Position', [0.36 0.045 0.28 0.042], ...
                  'FontSize', 10, ...
                  'Callback', @loadLowRiskExample, ...
                  'BackgroundColor', colors.success, ...
                  'ForegroundColor', colors.cardBg, ...
                  'FontWeight', 'bold');
        
        uicontrol('Parent', inputPanel, 'Style', 'pushbutton', ...
                  'String', '🗑️ Clear', ...
                  'Units', 'normalized', ...
                  'Position', [0.67 0.045 0.28 0.042], ...
                  'FontSize', 10, ...
                  'Callback', @clearInputs, ...
                  'BackgroundColor', colors.medGray);
    end
    
    function createModernControlPanel()
        controlPanel = uipanel('Parent', mainFig, ...
                               'Units', 'normalized', ...
                               'Position', [0.02 0.12 0.30 0.18], ...
                               'BackgroundColor', colors.cardBg, ...
                               'BorderType', 'line', ...
                               'BorderWidth', 1, ...
                               'HighlightColor', colors.medGray);
        
        uicontrol('Parent', controlPanel, 'Style', 'text', ...
                  'String', 'AI Model Selection', ...
                  'Units', 'normalized', ...
                  'Position', [0.05 0.78 0.9 0.15], ...
                  'FontSize', 14, 'FontWeight', 'bold', ...
                  'HorizontalAlignment', 'left', ...
                  'BackgroundColor', colors.cardBg, ...
                  'ForegroundColor', colors.textPrimary);
        
        handles.modelPopup = uicontrol('Parent', controlPanel, ...
                  'Style', 'popupmenu', ...
                  'String', {'Baseline Neural Network', ...
                            'Dropout Regularization (Recommended)', ...
                            'Early Stopping', ...
                            'SCG Optimization'}, ...
                  'Value', 2, ...
                  'Units', 'normalized', ...
                  'Position', [0.05 0.60 0.90 0.15], ...
                  'FontSize', 11, ...
                  'BackgroundColor', colors.lightGray);
        
        handles.predictBtn = uicontrol('Parent', controlPanel, ...
                  'Style', 'pushbutton', ...
                  'String', 'PREDICT MORTALITY RISK', ...
                  'Units', 'normalized', ...
                  'Position', [0.05 0.35 0.90 0.20], ...
                  'FontSize', 14, ...
                  'FontWeight', 'bold', ...
                  'ForegroundColor', colors.cardBg, ...
                  'BackgroundColor', colors.primary, ...
                  'Callback', @predictCallback);
        
        uicontrol('Parent', controlPanel, 'Style', 'pushbutton', ...
                  'String', 'Batch Prediction', ...
                  'Units', 'normalized', ...
                  'Position', [0.05 0.08 0.43 0.18], ...
                  'FontSize', 11, ...
                  'Callback', @batchPredictCallback, ...
                  'BackgroundColor', colors.lightGray);
        
        handles.exportBtn = uicontrol('Parent', controlPanel, ...
                  'Style', 'pushbutton', ...
                  'String', 'Export Report', ...
                  'Units', 'normalized', ...
                  'Position', [0.52 0.08 0.43 0.18], ...
                  'FontSize', 11, ...
                  'Enable', 'off', ...
                  'Callback', @exportCallback, ...
                  'BackgroundColor', colors.lightGray);
    end
    
    function createModernResultsPanel()
        resultsPanel = uipanel('Parent', mainFig, ...
                               'Units', 'normalized', ...
                               'Position', [0.33 0.12 0.66 0.76], ...
                               'BackgroundColor', colors.cardBg, ...
                               'BorderType', 'line', ...
                               'BorderWidth', 1, ...
                               'HighlightColor', colors.medGray);
        
        handles.resultsPanel = resultsPanel;
        
        ax = axes('Parent', resultsPanel, 'Position', [0.1 0.1 0.8 0.8], 'Visible', 'off');
        text(0.5, 0.5, {'Ready for Prediction', '', 'Enter patient data and click PREDICT to begin'}, ...
             'Parent', ax, 'HorizontalAlignment', 'center', ...
             'FontSize', 18, 'Color', colors.textSecondary, 'FontWeight', 'bold');
        axis(ax, [0 1 0 1]);
        handles.mainResultsAxes = ax;
    end
    
    function createModernFooter()
        footerPanel = uipanel('Parent', mainFig, ...
                              'Units', 'normalized', ...
                              'Position', [0 0 1 0.10], ...
                              'BackgroundColor', [0.98 0.98 0.99], ...
                              'BorderType', 'none');
        
        if isfield(handles, 'models') && ~isempty(handles.models)
            perfText = sprintf('Model Accuracy: Baseline %.1f%% | Dropout %.1f%% | Early-Stop %.1f%% | SCG-Opt %.1f%%', ...
                               handles.models.metrics_baseline_test.Accuracy*100, ...
                               handles.models.metrics_dropout_test.Accuracy*100, ...
                               handles.models.metrics_earlystop_test.Accuracy*100, ...
                               handles.models.metrics_scg_test.Accuracy*100);
        else
            perfText = 'Model Performance: Loading...';
        end
        
        uicontrol('Parent', footerPanel, 'Style', 'text', ...
                  'String', perfText, ...
                  'Units', 'normalized', ...
                  'Position', [0.02 0.65 0.96 0.25], ...
                  'FontSize', 11, 'FontWeight', 'bold', ...
                  'BackgroundColor', [0.98 0.98 0.99], ...
                  'ForegroundColor', colors.textPrimary, ...
                  'HorizontalAlignment', 'left');
        
        uicontrol('Parent', footerPanel, 'Style', 'text', ...
                  'String', 'For research and educational purposes only. Not a substitute for professional medical advice.', ...
                  'Units', 'normalized', ...
                  'Position', [0.02 0.35 0.96 0.25], ...
                  'FontSize', 11, ...
                  'ForegroundColor', colors.danger, ...
                  'BackgroundColor', [0.98 0.98 0.99], ...
                  'HorizontalAlignment', 'left');
        
        uicontrol('Parent', footerPanel, 'Style', 'text', ...
                  'String', '2025 Heart Failure Prediction System | Powered by Machine Learning', ...
                  'Units', 'normalized', ...
                  'Position', [0.02 0.05 0.96 0.25], ...
                  'FontSize', 10, ...
                  'BackgroundColor', [0.98 0.98 0.99], ...
                  'ForegroundColor', colors.textSecondary, ...
                  'HorizontalAlignment', 'center');
    end
    
    function loadHighRiskExample(~, ~)
        set(handles.input_age, 'String', '75');
        set(handles.input_anaemia, 'String', '1');
        set(handles.input_cpk, 'String', '582');
        set(handles.input_diabetes, 'String', '1');
        set(handles.input_ef, 'String', '20');
        set(handles.input_hbp, 'String', '1');
        set(handles.input_platelets, 'String', '265000');
        set(handles.input_creatinine, 'String', '1.9');
        set(handles.input_sodium, 'String', '130');
        set(handles.input_sex, 'String', '1');
        set(handles.input_smoking, 'String', '0');
        set(handles.input_time, 'String', '60');
    end
    
    function loadLowRiskExample(~, ~)
        set(handles.input_age, 'String', '50');
        set(handles.input_anaemia, 'String', '0');
        set(handles.input_cpk, 'String', '120');
        set(handles.input_diabetes, 'String', '0');
        set(handles.input_ef, 'String', '60');
        set(handles.input_hbp, 'String', '0');
        set(handles.input_platelets, 'String', '280000');
        set(handles.input_creatinine, 'String', '1.0');
        set(handles.input_sodium, 'String', '138');
        set(handles.input_sex, 'String', '0');
        set(handles.input_smoking, 'String', '0');
        set(handles.input_time, 'String', '180');
    end
    
    function clearInputs(~, ~)
        fields = {'age', 'anaemia', 'cpk', 'diabetes', 'ef', 'hbp', ...
                 'platelets', 'creatinine', 'sodium', 'sex', 'smoking', 'time'};
        for i = 1:length(fields)
            set(handles.(['input_' fields{i}]), 'String', '');
        end
        
        cla(handles.mainResultsAxes);
        set(handles.mainResultsAxes, 'Visible', 'off');
        text(0.5, 0.5, {'Cleared', '', 'Ready for new prediction'}, ...
             'Parent', handles.mainResultsAxes, ...
             'HorizontalAlignment', 'center', ...
             'FontSize', 16, 'Color', colors.textSecondary);
        axis(handles.mainResultsAxes, [0 1 0 1]);
        
        set(handles.exportBtn, 'Enable', 'off');
        handles.currentResult = [];
        guidata(mainFig, handles);
    end
    
    function predictCallback(~, ~)
        handles = guidata(mainFig);
        
        try
            patientData = [
                str2double(get(handles.input_age, 'String')), ...
                str2double(get(handles.input_anaemia, 'String')), ...
                str2double(get(handles.input_cpk, 'String')), ...
                str2double(get(handles.input_diabetes, 'String')), ...
                str2double(get(handles.input_ef, 'String')), ...
                str2double(get(handles.input_hbp, 'String')), ...
                str2double(get(handles.input_platelets, 'String')), ...
                str2double(get(handles.input_creatinine, 'String')), ...
                str2double(get(handles.input_sodium, 'String')), ...
                str2double(get(handles.input_sex, 'String')), ...
                str2double(get(handles.input_smoking, 'String')), ...
                str2double(get(handles.input_time, 'String'))
            ];
            
            if any(isnan(patientData))
                errordlg('Please fill in all fields!', 'Input Error');
                return;
            end
        catch
            errordlg('Invalid input!', 'Input Error');
            return;
        end
        
        modelIdx = get(handles.modelPopup, 'Value');
        modelNames = {'baseline', 'dropout', 'earlystop', 'scg'};
        selectedModel = modelNames{modelIdx};
        
        set(handles.predictBtn, 'String', 'Analyzing...', 'Enable', 'off');
        drawnow;
        
        try
            result = performPrediction(patientData, selectedModel, handles.models);
            handles.currentResult = result;
            guidata(mainFig, handles);
            
            displayModernResults(result, patientData);
            set(handles.exportBtn, 'Enable', 'on');
        catch ME
            errordlg(['Prediction error: ' ME.message], 'Error');
        end
        
        set(handles.predictBtn, 'String', 'PREDICT MORTALITY RISK', 'Enable', 'on');
    end
    
    function result = performPrediction(patientData, modelType, models)
        X_norm = (patientData - models.mu) ./ models.sigma;
        
        switch modelType
            case 'baseline'
                net = models.net_baseline;
                y_prob = net(X_norm')';
                if numel(y_prob) > 1, y_prob = y_prob(1); end
                modelName = 'Baseline Neural Network';
                metrics = models.metrics_baseline_test;
                
            case 'dropout'
                net = models.net_dropout;
                try
                    [~, scores] = classify(net, X_norm);
                    if isfield(models, 'dropoutPosClassIdx')
                        y_prob = double(scores(models.dropoutPosClassIdx));
                    else
                        y_prob = double(max(scores(:)));
                    end
                catch
                    y_prob = net(X_norm')';
                    if numel(y_prob) > 1, y_prob = y_prob(1); end
                end
                modelName = 'Dropout Regularization';
                metrics = models.metrics_dropout_test;
                
            case 'earlystop'
                net = models.net_earlystop;
                y_prob = net(X_norm')';
                if numel(y_prob) > 1, y_prob = y_prob(1); end
                modelName = 'Early Stopping';
                metrics = models.metrics_earlystop_test;
                
            case 'scg'
                net = models.net_scg;
                y_prob = net(X_norm')';
                if numel(y_prob) > 1, y_prob = y_prob(1); end
                modelName = 'SCG Optimization';
                metrics = models.metrics_scg_test;
        end
        
        y_prob = double(max(0, min(1, y_prob)));
        y_pred = double(y_prob > 0.5);
        
        if y_prob < 0.3
            riskLevel = 'Low'; riskColor = colors.success;
        elseif y_prob < 0.7
            riskLevel = 'Medium'; riskColor = colors.warning;
        else
            riskLevel = 'High'; riskColor = colors.danger;
        end
        
        result = struct('prediction', y_pred, 'probability', y_prob, ...
                       'riskLevel', riskLevel, 'riskColor', riskColor, ...
                       'confidence', abs(y_prob - 0.5) * 2, ...
                       'modelUsed', modelName, 'modelAccuracy', metrics.Accuracy, ...
                       'modelF1', metrics.F1, 'patientData', patientData);
    end
    
    function displayModernResults(result, patientData)
        handles = guidata(mainFig);
        
        delete(get(handles.resultsPanel, 'Children'));
        
        topPanel = uipanel('Parent', handles.resultsPanel, ...
                          'Units', 'normalized', ...
                          'Position', [0.02 0.72 0.96 0.26], ...
                          'BackgroundColor', result.riskColor, ...
                          'BorderType', 'none');
        
        if result.prediction == 1
            outcomeText = 'HIGH MORTALITY RISK';
        else
            outcomeText = 'LOW MORTALITY RISK';
        end
        
        uicontrol('Parent', topPanel, 'Style', 'text', ...
                  'String', outcomeText, ...
                  'Units', 'normalized', 'Position', [0.05 0.48 0.60 0.40], ...
                  'FontSize', 28, 'FontWeight', 'bold', ...
                  'BackgroundColor', result.riskColor, ...
                  'ForegroundColor', colors.cardBg, ...
                  'HorizontalAlignment', 'left');
        
        uicontrol('Parent', topPanel, 'Style', 'text', ...
                  'String', sprintf('Mortality Probability: %.1f%%  |  Confidence: %.1f%%', ...
                                   result.probability*100, result.confidence*100), ...
                  'Units', 'normalized', 'Position', [0.05 0.15 0.60 0.28], ...
                  'FontSize', 14, 'BackgroundColor', result.riskColor, ...
                  'ForegroundColor', colors.cardBg, ...
                  'HorizontalAlignment', 'left');
        
        modelPanel = uipanel('Parent', topPanel, ...
                            'Units', 'normalized', ...
                            'Position', [0.68 0.52 0.29 0.38], ...
                            'BackgroundColor', colors.cardBg, ...
                            'BorderType', 'none');
        
        uicontrol('Parent', modelPanel, 'Style', 'text', ...
                  'String', 'MODEL', ...
                  'Units', 'normalized', 'Position', [0.05 0.62 0.9 0.32], ...
                  'FontSize', 12, 'FontWeight', 'bold', ...
                  'BackgroundColor', colors.cardBg, ...
                  'ForegroundColor', colors.textSecondary, ...
                  'HorizontalAlignment', 'center');
        
        uicontrol('Parent', modelPanel, 'Style', 'text', ...
                  'String', result.modelUsed, ...
                  'Units', 'normalized', 'Position', [0.05 0.10 0.9 0.48], ...
                  'FontSize', 11, 'FontWeight', 'bold', ...
                  'BackgroundColor', colors.cardBg, ...
                  'ForegroundColor', colors.textPrimary, ...
                  'HorizontalAlignment', 'center');
        
        accPanel = uipanel('Parent', topPanel, ...
                          'Units', 'normalized', ...
                          'Position', [0.68 0.10 0.29 0.38], ...
                          'BackgroundColor', colors.cardBg, ...
                          'BorderType', 'none');
        
        uicontrol('Parent', accPanel, 'Style', 'text', ...
                  'String', 'ACCURACY', ...
                  'Units', 'normalized', 'Position', [0.05 0.62 0.9 0.32], ...
                  'FontSize', 12, 'FontWeight', 'bold', ...
                  'BackgroundColor', colors.cardBg, ...
                  'ForegroundColor', colors.textSecondary, ...
                  'HorizontalAlignment', 'center');
        
        uicontrol('Parent', accPanel, 'Style', 'text', ...
                  'String', sprintf('%.1f%%', result.modelAccuracy*100), ...
                  'Units', 'normalized', 'Position', [0.05 0.10 0.9 0.48], ...
                  'FontSize', 18, 'FontWeight', 'bold', ...
                  'BackgroundColor', colors.cardBg, ...
                  'ForegroundColor', colors.primary, ...
                  'HorizontalAlignment', 'center');
        
        keyFeatures = [1, 5, 8, 9];
        featureNames = {'Age (years)', 'Ejection Fraction (%)', ...
                       'Serum Creatinine (mg/dL)', 'Serum Sodium (mEq/L)'};

        positions = {[0.08 0.40 0.38 0.28], [0.56 0.40 0.38 0.28], ...
                    [0.08 0.06 0.38 0.28], [0.56 0.06 0.38 0.28]};
        
        for i = 1:4
            ax = axes('Parent', handles.resultsPanel, ...
                     'Position', positions{i});
            
            featureIdx = keyFeatures(i);
            patientValue = patientData(featureIdx);
            
            if ~isempty(handles.populationData) && height(handles.populationData) > 0
                popData = handles.populationData{:, featureIdx};
            else
                popData = generateSimulatedPopulation(featureIdx);
            end
            
            histogram(ax, popData, 30, 'FaceColor', colors.primary, ...
                     'FaceAlpha', 0.6, 'EdgeColor', 'none');
            hold(ax, 'on');
            
            yLim = get(ax, 'YLim');
            plot(ax, [patientValue patientValue], [0 yLim(2)], ...
                 'Color', result.riskColor, 'LineWidth', 4, 'LineStyle', '--');
            
            meanVal = mean(popData);
            plot(ax, [meanVal meanVal], [0 yLim(2)*0.5], ...
                 'Color', colors.darkGray, 'LineWidth', 2, 'LineStyle', ':');
            
            title(ax, featureNames{i}, 'FontSize', 12, 'FontWeight', 'bold', ...
                  'Color', colors.textPrimary);
            xlabel(ax, 'Value', 'FontSize', 10);
            ylabel(ax, 'Frequency', 'FontSize', 10);
            grid(ax, 'on');
            set(ax, 'GridAlpha', 0.15, 'FontSize', 9);
            
            if i == 1
                legend(ax, {'Population', 'Patient', 'Mean'}, ...
                      'Location', 'northeast', 'FontSize', 9);
            end
            
            percentile = sum(popData <= patientValue) / length(popData) * 100;
            text(ax, 0.98, 0.95, sprintf('%.0fth %%ile', percentile), ...
                 'Units', 'normalized', 'FontSize', 9, ...
                 'HorizontalAlignment', 'right', 'VerticalAlignment', 'top', ...
                 'BackgroundColor', colors.cardBg, 'EdgeColor', colors.medGray, ...
                 'Margin', 2, 'FontWeight', 'bold', 'Color', result.riskColor);
            
            hold(ax, 'off');
        end
    end
    
    function popData = generateSimulatedPopulation(featureIdx)
        switch featureIdx
            case 1
                popData = 40 + 40*rand(299, 1);
            case 5
                popData = 20 + 50*rand(299, 1);
            case 8
                popData = 0.5 + 2*rand(299, 1);
            case 9
                popData = 125 + 20*rand(299, 1);
            otherwise
                popData = randn(299, 1);
        end
    end
    
    function batchPredictCallback(~, ~)
        [filename, pathname] = uigetfile({'*.csv;*.xlsx', 'Data Files'}, ...
                                         'Select Patient Data File');
        if filename == 0, return; end
        
        try
            fullpath = fullfile(pathname, filename);
            if endsWith(filename, '.csv')
                data = readtable(fullpath);
            else
                data = readtable(fullpath, 'Sheet', 1);
            end
            
            if size(data, 2) < 12
                errordlg('File must contain at least 12 columns!', 'Data Error');
                return;
            end
            
            patientsData = table2array(data(:, 1:12));
            nPatients = size(patientsData, 1);
            
            handles = guidata(mainFig);
            modelIdx = get(handles.modelPopup, 'Value');
            modelNames = {'baseline', 'dropout', 'earlystop', 'scg'};
            selectedModel = modelNames{modelIdx};
            
            h = waitbar(0, 'Processing batch predictions...');
            results = cell(nPatients, 1);
            for i = 1:nPatients
                waitbar(i/nPatients, h);
                results{i} = performPrediction(patientsData(i, :), selectedModel, handles.models);
            end
            close(h);
            
            highRiskCount = sum(cellfun(@(x) x.prediction, results) == 1);
            avgProb = mean(cellfun(@(x) x.probability, results));
            
            msgbox(sprintf(['Batch Complete!\n\nTotal: %d\nHigh Risk: %d (%.1f%%)\n' ...
                           'Low Risk: %d (%.1f%%)\nAvg Probability: %.1f%%'], ...
                           nPatients, highRiskCount, highRiskCount/nPatients*100, ...
                           nPatients-highRiskCount, (nPatients-highRiskCount)/nPatients*100, ...
                           avgProb*100), 'Batch Results');
            
            saveBatchResults(results, patientsData, fullpath);
        catch ME
            errordlg(['Error: ' ME.message], 'File Error');
        end
    end
    
    function saveBatchResults(results, patientsData, originalFile)
        [~, name, ~] = fileparts(originalFile);
        outputFile = [name '_predictions.csv'];
        [filename, pathname] = uiputfile('*.csv', 'Save Results', outputFile);
        
        if filename == 0, return; end
        
        outputTable = array2table(patientsData, ...
            'VariableNames', {'Age', 'Anaemia', 'CPK', 'Diabetes', 'EF', 'HBP', ...
                             'Platelets', 'SerumCreatinine', 'SerumSodium', ...
                             'Sex', 'Smoking', 'FollowUpTime'});
        
        predictions = cellfun(@(x) x.prediction, results);
        probabilities = cellfun(@(x) x.probability, results);
        riskLevels = cellfun(@(x) x.riskLevel, results, 'UniformOutput', false);
        
        outputTable.Prediction = predictions;
        outputTable.MortalityProbability = probabilities;
        outputTable.RiskLevel = riskLevels;
        
        writetable(outputTable, fullfile(pathname, filename));
        msgbox('Results saved!', 'Success');
    end
    
    function exportCallback(~, ~)
        handles = guidata(mainFig);
        if isempty(handles.currentResult)
            msgbox('No results to export!', 'Error', 'warn');
            return;
        end
        
        [filename, pathname] = uiputfile('*.txt', 'Save Report', 'prediction_report.txt');
        if filename == 0, return; end
        
        result = handles.currentResult;
        report = sprintf(['HEART FAILURE MORTALITY PREDICTION REPORT\n' ...
                         '==========================================\n\n' ...
                         'Date: %s\n\n' ...
                         'PREDICTION: %s\n' ...
                         'Mortality Probability: %.1f%%\n' ...
                         'Risk Level: %s\n' ...
                         'Confidence: %.1f%%\n\n' ...
                         'Model: %s\n' ...
                         'Accuracy: %.1f%%\n' ...
                         'F1-Score: %.4f\n'], ...
                         datestr(now), ...
                         iif(result.prediction==1, 'High Risk', 'Low Risk'), ...
                         result.probability*100, result.riskLevel, ...
                         result.confidence*100, result.modelUsed, ...
                         result.modelAccuracy*100, result.modelF1);
        
        fid = fopen(fullfile(pathname, filename), 'w');
        fprintf(fid, '%s', report);
        fclose(fid);
        msgbox('Report exported!', 'Success');
    end
    
    function closeGUI(~, ~)
        selection = questdlg('Exit?', 'Confirm', 'Yes', 'No', 'No');
        if strcmp(selection, 'Yes')
            delete(mainFig);
        end
    end
    
    function out = iif(condition, trueVal, falseVal)
        if condition, out = trueVal; else, out = falseVal; end
    end

end